Essentian Functions:

1. NumPy: Numerical computing (arrays, linear algebra, math operations)

2. SymPy: Symbolic mathematics (exact computations with symbols)

3. Matplotlib: Basic plotting and visualization

4. Seaborn: Statistical visualization (builds on Matplotlib, better defaults)

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


**1. Scalar & Array Operations (Redo Section with Your Own Values):**
   
   --> Run the given code with scalar = 3.7 and a new array of at least 6 elements.
   
   --> Show outputs of all built-in mathematical functions (sin, cos, tan, etc.). *italicised text*


In [ ]:
#Scalar & Array Operations
scalar =  3.7
arr = np.array([1.1, 2.5, -3, 4, 9,11])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)

sin: [ 0.89120736  0.59847214 -0.14112001 -0.7568025   0.41211849 -0.99999021]
cos: [ 0.45359612 -0.80114362 -0.9899925  -0.65364362 -0.91113026  0.0044257 ]
tan: [ 1.96475966e+00 -7.47022297e-01  1.42546543e-01  1.15782128e+00
 -4.52315659e-01 -2.25950846e+02]


**2. 2×2 Matrix Calculations (Already Done in Class):**

   *--> Study and understand the example code given for trigonometric, exponential, logarithmic, and rounding operations on a 2×2 matrix.*


In [ ]:
# Creating a 2x2 matrix
matrix = np.array([[1.5, 3.9], [-5, 7]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[ 1.5  3.9]
 [-5.   7. ]]

sin:
 [[ 0.99749499 -0.68776616]
 [ 0.95892427  0.6569866 ]]

cos:
 [[ 0.0707372  -0.7259323 ]
 [ 0.28366219  0.75390225]]

tan:
 [[14.10141995  0.94742465]
 [ 3.38051501  0.87144798]]

asine:
 [[ 0.2159605   0.5909412 ]
 [-0.79560295  1.57079633]]

acosine:
 [[1.35483583 0.97985513]
 [2.36639928 0.        ]]

atangent:
 [[ 0.98279372  1.31979364]
 [-1.37340077  1.42889927]]

exp:
 [[4.48168907e+00 4.94024491e+01]
 [6.73794700e-03 1.09663316e+03]]

log (natural):
 [[0.40546511 1.36097655]
 [       nan 1.94591015]]

round:
 [[ 2.  4.]
 [-5.  7.]]

floor:
 [[ 1.  3.]
 [-5.  7.]]

ceil:
 [[ 2.  4.]
 [-5.  7.]]


/tmp/ipython-input-3064876010.py:14: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)


**3. Apply the Same Operations on a 3×2 Matrix**

    --> Create a 3×2 matrix with custom values.

    --> Perform and display results of:
        --> Trigonometric functions
        --> Exponential & logarithmic functions
        --> Absolute value & square root
        --> Remainder when divided by 2
        --> Rounding (round, floor, ceil)


📌 Make sure to clip inputs where needed to avoid math errors (e.g., arcsin/arccos domain issues).

In [ ]:
# 3×2 Matrix Calculations
matrix = np.array([[1, 2.2], [3, 4],[-5,6]])
# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[ 1.   2.2]
 [ 3.   4. ]
 [-5.   6. ]]

sin:
 [[ 0.84147098  0.8084964 ]
 [ 0.14112001 -0.7568025 ]
 [ 0.95892427 -0.2794155 ]]

cos:
 [[ 0.54030231 -0.58850112]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]

tan:
 [[ 1.55740772 -1.37382306]
 [-0.14254654  1.15782128]
 [ 3.38051501 -0.29100619]]

asine:
 [[ 0.16744808  0.37542361]
 [ 0.52359878  0.72972766]
 [-0.98511078  1.57079633]]

acosine:
 [[1.40334825 1.19537272]
 [1.04719755 0.84106867]
 [2.55590711 0.        ]]

atangent:
 [[ 0.78539816  1.14416883]
 [ 1.24904577  1.32581766]
 [-1.37340077  1.40564765]]

exp:
 [[2.71828183e+00 9.02501350e+00]
 [2.00855369e+01 5.45981500e+01]
 [6.73794700e-03 4.03428793e+02]]

log (natural):
 [[0.         0.78845736]
 [1.09861229 1.38629436]
 [       nan 1.79175947]]

abs:
 [[1.  2.2]
 [3.  4. ]
 [5.  6. ]]

sqrt:
 [[1.         1.4832397 ]
 [1.73205081 2.        ]
 [       nan 2.44948974]]

rem (remainder when divided by 2):
 [[1.  0.2]
 [1.  0. ]
 [1.  0. ]]

round:
 [[ 1.  

/tmp/ipython-input-275618145.py:13: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)
/tmp/ipython-input-275618145.py:17: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)


**4. Vector Functions**

    --> Understand the operations on the 1D vector shown in the notebook.



*Task:* **Perform Same Operations on a 2×3 Matrix**

    --> Your 2×3 matrix can have float values (e.g., 2.1, 4.7…).

    --> Implement and display:
        
        --> Max & Min (with indices)
        --> Vector length
        --> Sorted version (both row-wise descending and entire matrix descending)
        --> Sum, Product
        --> Median, Mean, Standard Deviation


📌 Hint: Use np.sort() with axis=1 for row-wise sorting. Use .flatten() for entire matrix sorting.


In [ ]:
# Sample vector (2×3)
vec = np.array([[1.7, 2.2,3.5], [3.3, 4.6,5.5]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 5.5 at index 5
Min value: 1.7 at index 0
Length of vector: 2
Sorted vector: [[1.7 2.2 3.5]
 [3.3 4.6 5.5]]
Sum of elements: 20.799999999999997
Product of elements: 1092.8840999999998
Median value: 3.4
Mean value: 3.4666666666666663
Standard deviation: 1.302134998974974
