In [3]:

# Student ID = 07
# d1 = 7, d2 = 0


import numpy as np
from sympy import Matrix


# Question 1: Personal Matrix A

A = np.array([[7, 0],
              [0, 7]])
print("Matrix A:\n", A, "\n")


# Question 2: Analysis of Matrix A

print("Shape of A:", A.shape)

det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

eig_A, eigvec_A = np.linalg.eig(A)
print("Eigenvalues of A:", eig_A)
print("Eigenvectors of A:\n", eigvec_A)

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is not invertible")


# Question 3: Value Change Experiment
# Changed element A[0,0] by adding +1
# A[0,0] = 7 → 8

B = np.array([[8, 0],
              [0, 7]])
print("\nMatrix B (after changing A[0,0] + 1):\n", B, "\n")


# Question 4: Analysis of Matrix B

print("Shape of B:", B.shape)

det_B = np.linalg.det(B)
print("Determinant of B:", det_B)

rank_B = np.linalg.matrix_rank(B)
print("Rank of B:", rank_B)

eig_B, eigvec_B = np.linalg.eig(B)
print("Eigenvalues of B:", eig_B)
print("Eigenvectors of B:\n", eigvec_B)

if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Inverse of B:\n", inv_B)
else:
    print("Matrix B is not invertible")


# COMPARISON & EXPLANATION


# 1. Determinant Comparison:
#    det(A) = 49, det(B) = 56
#    Determinant increased because one diagonal value was increased by 1.
#    For diagonal matrices, determinant = product of diagonal elements.

# 2. Rank Comparison:
#    Rank(A) = 2 and Rank(B) = 2
#    Rank did not change because rows and columns are still linearly independent.

# 3. Eigenvalues Comparison:
#    Eigenvalues of A = [7, 7]
#    Eigenvalues of B = [8, 7]
#    Only the eigenvalue related to the changed diagonal element increased.

# 4. Invertibility:
#    Both A and B are invertible because their determinants are not zero.

# 5. Ease of Inversion:
#    Both matrices are easy to invert.
#    Matrix A is slightly simpler because both diagonal values are equal.


Matrix A:
 [[7 0]
 [0 7]] 

Shape of A: (2, 2)
Determinant of A: 48.99999999999999
Rank of A: 2
Eigenvalues of A: [7. 7.]
Eigenvectors of A:
 [[1. 0.]
 [0. 1.]]
Inverse of A:
 [[0.14285714 0.        ]
 [0.         0.14285714]]

Matrix B (after changing A[0,0] + 1):
 [[8 0]
 [0 7]] 

Shape of B: (2, 2)
Determinant of B: 55.99999999999997
Rank of B: 2
Eigenvalues of B: [8. 7.]
Eigenvectors of B:
 [[1. 0.]
 [0. 1.]]
Inverse of B:
 [[0.125      0.        ]
 [0.         0.14285714]]
